# Day 3 — Pandas Basics

This notebook introduces Pandas using a synthetic XR moral decision-making dataset.

Topics covered:
- Creating a DataFrame
- Inspecting data
- Selecting columns
- Filtering rows
- Creating derived variables
- Basic descriptive statistics
- Frequency counts

In [40]:
!ls /content

sample_data  vr_moral_dilemma_day3.csv

In [41]:
import pandas as pd

In [42]:
df = pd.read_csv("/content/vr_moral_dilemma_day3.csv")

In [43]:
df

,participant_id,condition,decision_time,choice,embodiment_score,conflict_score,gaze_switches
0,101,sheep,3.2,save_sheep,6.1,4.1,9
1,102,farmer,6.1,save_farmer,5.4,7.2,21
2,103,sheep,5.4,save_farmer,6.7,6.3,17
3,104,farmer,2.7,save_sheep,4.9,3.8,6

In [44]:
# number of columns and rows
df.shape

(4, 7)

In [53]:
df[["participant_id","condition","choice"]]

   participant_id condition       choice
0             101     sheep   save_sheep
1             102    farmer  save_farmer
2             103     sheep  save_farmer
3             104    farmer   save_sheep

In [54]:
df[df["decision_time"] > 4]

,participant_id,condition,decision_time,choice,embodiment_score,conflict_score,gaze_switches
1,102,farmer,6.1,save_farmer,5.4,7.2,21
2,103,sheep,5.4,save_farmer,6.7,6.3,17

In [55]:
df[df["condition"] == "farmer"]

,participant_id,condition,decision_time,choice,embodiment_score,conflict_score,gaze_switches
1,102,farmer,6.1,save_farmer,5.4,7.2,21
3,104,farmer,2.7,save_sheep,4.9,3.8,6

In [56]:
# creating a new column: interesting trial
df["interesting_trial"] = ((df["embodiment_score"] > 6) & (df["conflict_score"] < 3))

In [62]:
df["decision_time"].mean()

np.float64(4.3500000000000005)

In [63]:
df["embodiment_score"].median()

5.75

In [59]:
df["choice"].value_counts()

choice
save_sheep     2
save_farmer    2
Name: count, dtype: int64

In [60]:
df["condition"].value_counts()

condition
sheep     2
farmer    2
Name: count, dtype: int64

In [61]:
# Average decision time in sheep condition

sheep_df = df[df["condition"] == "sheep"]

sheep_df["decision_time"].mean()

np.float64(4.300000000000001)