# Day 5 — Grouping and Aggregation

This notebook explores condition-level patterns in a synthetic XR moral decision-making dataset using Pandas grouping and aggregation tools.

Topics covered:
- Grouping data with `groupby()`
- Calculating group-level summary statistics
- Applying multiple aggregation functions
- Counting categorical outcomes within groups
- Comparing behavioral measures across experimental conditions

The goal is to move from participant-level observations to condition-level summaries that can later support statistical analysis.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/vr_moral_dilemma_clean.csv")

In [7]:
cond_grp = df.groupby("condition")

In [5]:
cond_grp["decision_time"].mean()

condition
farmer    4.10
sheep     4.05
Name: decision_time, dtype: float64

In [9]:
cond_grp["embodiment_score"].mean()

condition
farmer    5.033333
sheep     6.500000
Name: embodiment_score, dtype: float64

In [10]:
cond_grp["conflict_score"].mean()

condition
farmer    4.566667
sheep     5.450000
Name: conflict_score, dtype: float64

In [12]:
df["condition"].value_counts()

condition
farmer    3
sheep     2
Name: count, dtype: int64

In [17]:
cond_grp["decision_time"].agg(["mean","median", "std"] )

           mean  median       std
condition
farmer     4.10    3.60  1.609348
sheep      4.05    4.05  0.919239

> The sheep and farmer conditions showed relatively similar mean decision times, although the farmer condition exhibited greater variability, as indicated by a larger standard deviation. In contrast, the sheep condition showed a higher mean conflict score than the farmer condition.

In [19]:
cond_grp[["decision_time", "conflict_score"]].agg(["mean", "std"])

          decision_time           conflict_score
                   mean       std           mean       std
condition
farmer             4.10  1.609348       4.566667  2.081666
sheep              4.05  0.919239       5.450000  0.919239

In [20]:
cond_grp["choice"].value_counts()

condition  choice
farmer     save_sheep     2
           save_farmer    1
sheep      save_farmer    1
           save_sheep     1
Name: count, dtype: int64

In [22]:
summary_table = cond_grp.agg(
    decision_time_mean=("decision_time", "mean"),
    decision_time_std=("decision_time", "std"),
    conflict_mean=("conflict_score", "mean")
)

summary_table

           decision_time_mean  decision_time_std  conflict_mean
condition
farmer                   4.10           1.609348       4.566667
sheep                    4.05           0.919239       5.450000